language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - composer self-update
  - composer config -g github-oauth.github.com ab3ce6ab2c029c95bd8ffecb8e7d0e295779a792
  - composer global require thephpeffect/triggr-php:dev-master
  
install:
  - composer install --no-progress --profile

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: "nathans@thephpeffect.com"
